---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
 #inventory:
 #  links:
 #    hosts: inventory.yml
verifier:
  name: testinfra #ansible
