---
# tasks file for apache
- name: Print some data
  copy:
    content: "{{ foo }}"
    dest: /tmp/test_file

- name: Install package
  package:
    name:
    - htop
    - tmux
    state: present

- name: Install nginx
  package:
    name: nginx
    state: present

#- name: Ensure started nginx
#  become: true
#  service:
#    name: nginx
#    state: started
