---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
    image: ubuntu:latest #quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
