---
- name: Execute setup.yml tasks
  include_tasks: setup.yml
  when: setup | bool

- name: Execute always.yml tasks
  include_tasks: always.yml

- name: Execute teardown.yml tasks
  include_tasks: teardown.yml
  when: teardown| default('false') | bool

