---
- name: This is setup.yml file
  shell: echo this is setup.yml file && sleep 5
  register: cmd_res

- debug:
    var: cmd_res.delta

- name: Echo in loop
  command: echo  "{{ item }}"
  with_items:
    - line1
    - line2
    - line3

- name: Create file
  file:
    path: "/tmp/{{ item.namefoo }}"
    state: "{{ item.statebar }}"
  with_items:
    - { namefoo: ansible, statebar: directory }
    - { namefoo: ansible_2.txt, statebar: touch }
    - { namefoo: ansible_3.txt, statebar: touch }

- name: Install OS packages
  become: true
  package:
    name:
      - htop
      - vim
      - tmux
      - unzip

- name: Compose secret config file
  copy:
    dest: /tmp/passwd
    content: "This is super duper secret password: {{ password }}"
