---
- name: Prepare user
  hosts: server
  become: true
  roles:
    - { role: os_prepare, tags: [prepare] }

- name: Prepare user DUPLICATE INVOCATION
  hosts: server
  become: true
  roles:
    - { role: os_prepare, tags: [another_tag] }


- name: Upload some files
  hosts: application
  roles:
    - role: upload
